version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: piccha-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - piccha-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: piccha-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - piccha-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: piccha-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - piccha-net

  clickhouse:
    image: clickhouse/clickhouse-server:23.12
    container_name: piccha-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_/var/lib/clickhouse  # ← добавлен том для данных
      - ./config/clickhouse:/etc/clickhouse-server/config.d  # ← монтируем папку, не файл
    command: --config-file=/etc/clickhouse-server/config.xml  # ← принудительная инициализация
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - piccha-net

  grafana:
    image: grafana/grafana:10.0.0
    container_name: piccha-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - clickhouse
    networks:
      - piccha-net

volumes:
  mongo_data:
  clickhouse_data:  # ← добавлен том для ClickHouse

networks:
  piccha-net:
    driver: bridge