apiVersion: 1

datasources:
  - name: clickhouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: false
    isDefault: true
    jsonData:
      defaultDatabase: piccha_raw
      addCorsHeader: true
    version: 1
    editable: true